# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitor', '0002_dancer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('date_of_start', models.DateField(verbose_name='Date of Competition')),
                ('end_date_of_registration', models.DateField(verbose_name='Registration Deadline')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='competitor.Studio')),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarks', models.IntegerField(verbose_name='Marks')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_group', models.CharField(max_length=256, verbose_name='Name')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('time', models.TimeField(verbose_name='Time')),
                ('max_per_heat', models.IntegerField(default=0, verbose_name='Max Couples per Heat')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(verbose_name='Place')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='competition.Couple')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='competition.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Round Number')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='competition.Event')),
            ],
        ),
        migrations.AddField(
            model_name='couple',
            name='events',
            field=models.ManyToManyField(to='competition.Event'),
        ),
        migrations.AddField(
            model_name='couple',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_follow', to='competitor.Dancer'),
        ),
        migrations.AddField(
            model_name='couple',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_lead', to='competitor.Dancer'),
        ),
        migrations.AddField(
            model_name='couple',
            name='rounds',
            field=models.ManyToManyField(to='competition.Round'),
        ),
    ]
