# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='competition.Competition'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
