# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20171218_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='skill_group',
            field=models.CharField(max_length=256, verbose_name='Skill Group'),
        ),
    ]
