# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20171122_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalistPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(verbose_name='Place')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Event')),
            ],
        ),
    ]
