# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0015_auto_20171219_1621'),
        ('competition', '0004_auto_20171219_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='judges',
            field=models.ManyToManyField(to='competitor.Dancer'),
        ),
    ]
