# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0001_initial'),
        ('competition', '0004_finalistplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(related_name='couples', to='competition.Event')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_follow', to='competitor.Dancer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_lead', to='competitor.Dancer')),
            ],
        ),
    ]
