# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_couple'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalistplace',
            name='couple',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='competition.Couple'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalistplace',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='competition.Event'),
        ),
    ]
