# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0015_auto_20171219_1621'),
        ('competition', '0005_competition_judges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Logistic'), (1, 'Judge')], verbose_name='Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='judges',
        ),
        migrations.AddField(
            model_name='staff',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='competition.Competition'),
        ),
        migrations.AddField(
            model_name='staff',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='competitor.Dancer'),
        ),
    ]
