# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20171220_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Current'),
        ),
        migrations.AddField(
            model_name='round',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Current'),
        ),
    ]
