# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20171221_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='competition.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competition.Couple')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competition.Round')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='competition.Performance'),
        ),
    ]
