# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20171221_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='begun',
            field=models.BooleanField(default=False, verbose_name='Begun'),
        ),
    ]
