# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_competition_event_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='totalMarks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marks'),
        ),
    ]
