# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_auto_20171223_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='events',
            field=models.ManyToManyField(related_name='couples', to='competition.Event'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='rounds',
            field=models.ManyToManyField(blank=True, null=True, to='competition.Round'),
        ),
    ]
