# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0015_auto_20171223_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='rounds',
            field=models.ManyToManyField(blank=True, related_name='couples', to='competition.Round'),
        ),
    ]
