# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_auto_20171223_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='couples', to='competition.Competition'),
            preserve_default=False,
        ),
    ]
