# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_round_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='comp_number',
            field=models.IntegerField(default=1, verbose_name='Competition Number'),
            preserve_default=False,
        ),
    ]
