# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_couple_comp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couple',
            old_name='comp_number',
            new_name='couple_number',
        ),
    ]
