# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_couple_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='checked_in',
            field=models.ManyToManyField(related_name='checked_in', to='competition.Round'),
        ),
    ]
