# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-02 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0025_dance_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dances', to='competition.Event'),
        ),
    ]
