# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0008_auto_20171205_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='country',
            field=models.IntegerField(choices=[(0, 'Afghanistan'), (1, 'Albania'), (2, 'Algeria'), (3, 'Andorra'), (4, 'Angola'), (5, 'Antigua and Barbuda'), (6, 'Argentina'), (7, 'Armenia'), (8, 'Aruba'), (9, 'Australia'), (10, 'Austria'), (11, 'Azerbaijan'), (12, 'Bahamas, The'), (13, 'Bahrain'), (14, 'Bangladesh'), (15, 'Barbados'), (16, 'Belarus'), (17, 'Belgium'), (18, 'Belize'), (19, 'Benin'), (20, 'Bhutan'), (21, 'Bolivia'), (22, 'Bosnia and Herzegovina'), (23, 'Botswana'), (24, 'Brazil'), (25, 'Brunei'), (26, 'Bulgaria'), (27, 'Burkina Faso'), (28, 'Burma'), (29, 'Burundi'), (30, 'Cambodia'), (31, 'Cameroon'), (32, 'Canada'), (33, 'Cabo Verde'), (34, 'Central African Republic'), (35, 'Chad'), (36, 'Chile'), (37, 'China'), (38, 'Colombia'), (39, 'Comoros'), (40, 'Congo, Democratic Republic of the'), (41, 'Congo, Republic of the'), (42, 'Costa Rica'), (43, "Cote d'Ivoire"), (44, 'Croatia'), (45, 'Cuba'), (46, 'Curacao'), (47, 'Cyprus'), (48, 'Czechia'), (49, 'Denmark'), (50, 'Djibouti'), (51, 'Dominica'), (52, 'Dominican Republic'), (53, 'East Timor (see Timor-Leste)'), (54, 'Ecuador'), (55, 'Egypt'), (56, 'El Salvador'), (57, 'Equatorial Guinea'), (58, 'Eritrea'), (59, 'Estonia'), (60, 'Ethiopia'), (61, 'Fiji'), (62, 'Finland'), (63, 'France'), (64, 'Gabon'), (65, 'Gambia, The'), (66, 'Georgia'), (67, 'Germany'), (68, 'Ghana'), (69, 'Greece'), (70, 'Grenada'), (71, 'Guatemala'), (72, 'Guinea'), (73, 'Guinea-Bissau'), (74, 'Guyana'), (75, 'Haiti'), (76, 'Holy See'), (77, 'Honduras'), (78, 'Hong Kong'), (79, 'Hungary'), (80, 'Iceland'), (81, 'India'), (82, 'Indonesia'), (83, 'Iran'), (84, 'Iraq'), (85, 'Ireland'), (86, 'Israel'), (87, 'Italy'), (88, 'Jamaica'), (89, 'Japan'), (90, 'Jordan'), (91, 'Kazakhstan'), (92, 'Kenya'), (93, 'Kiribati'), (94, 'Korea, North'), (95, 'Korea, South'), (96, 'Kosovo'), (97, 'Kuwait'), (98, 'Kyrgyzstan'), (99, 'Laos'), (100, 'Latvia'), (101, 'Lebanon'), (102, 'Lesotho'), (103, 'Liberia'), (104, 'Libya'), (105, 'Liechtenstein'), (106, 'Lithuania'), (107, 'Luxembourg'), (108, 'Macau'), (109, 'Macedonia'), (110, 'Madagascar'), (111, 'Malawi'), (112, 'Malaysia'), (113, 'Maldives'), (114, 'Mali'), (115, 'Malta'), (116, 'Marshall Islands'), (117, 'Mauritania'), (118, 'Mauritius'), (119, 'Mexico'), (120, 'Micronesia'), (121, 'Moldova'), (122, 'Monaco'), (123, 'Mongolia'), (124, 'Montenegro'), (125, 'Morocco'), (126, 'Mozambique'), (127, 'Namibia'), (128, 'Nauru'), (129, 'Nepal'), (130, 'Netherlands'), (131, 'New Zealand'), (132, 'Nicaragua'), (133, 'Niger'), (134, 'Nigeria'), (135, 'North Korea'), (136, 'Norway'), (137, 'Oman'), (138, 'Pakistan'), (139, 'Palau'), (140, 'Palestinian Territories'), (141, 'Panama'), (142, 'Papua New Guinea'), (143, 'Paraguay'), (144, 'Peru'), (145, 'Philippines'), (146, 'Poland'), (147, 'Portugal'), (148, 'Qatar'), (149, 'Romania'), (150, 'Russia'), (151, 'Rwanda'), (152, 'Saint Kitts and Nevis'), (153, 'Saint Lucia'), (154, 'Saint Vincent and the Grenadines'), (155, 'Samoa'), (156, 'San Marino'), (157, 'Sao Tome and Principe'), (158, 'Saudi Arabia'), (159, 'Senegal'), (160, 'Serbia'), (161, 'Seychelles'), (162, 'Sierra Leone'), (163, 'Singapore'), (164, 'Sint Maarten'), (165, 'Slovakia'), (166, 'Slovenia'), (167, 'Solomon Islands'), (168, 'Somalia'), (169, 'South Africa'), (170, 'South Korea'), (171, 'South Sudan'), (172, 'Spain'), (173, 'Sri Lanka'), (174, 'Sudan'), (175, 'Suriname'), (176, 'Swaziland'), (177, 'Sweden'), (178, 'Switzerland'), (179, 'Syria'), (180, 'Taiwan'), (181, 'Tajikistan'), (182, 'Tanzania'), (183, 'Thailand'), (184, 'Timor-Leste'), (185, 'Togo'), (186, 'Tonga'), (187, 'Trinidad and Tobago'), (188, 'Tunisia'), (189, 'Turkey'), (190, 'Turkmenistan'), (191, 'Tuvalu'), (192, 'Uganda'), (193, 'Ukraine'), (194, 'United Arab Emirates'), (195, 'United Kingdom'), (196, 'United States'), (197, 'Uruguay'), (198, 'Uzbekistan'), (199, 'Vanuatu'), (200, 'Venezuela'), (201, 'Vietnam'), (202, 'Yemen'), (203, 'Zambia'), (204, 'Zimbabwe')], default=0, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studio',
            name='association_pin',
            field=models.IntegerField(unique=True, verbose_name='Studio PIN'),
        ),
    ]
