# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0009_auto_20171205_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name'),
        ),
    ]
