# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0010_auto_20171205_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_studio', to='competitor.Dancer'),
        ),
        migrations.AlterField(
            model_name='request',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_requests', to='competitor.Studio'),
        ),
    ]
