# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0014_auto_20171219_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='judging_pin',
            field=models.IntegerField(unique=True, verbose_name='Judging Pin'),
        ),
    ]
