# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0015_auto_20171219_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='judging_pin',
            field=models.IntegerField(unique=True, verbose_name='Identification Pin'),
        ),
    ]
